name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [ opened, reopened, synchronize ]

jobs:
  build:

    runs-on: ubuntu-latest

    container: node:14.20-bullseye

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code from repository
      uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build
    - run: npm run pretest
#    - run: npm test:ci:mysql

    # Setup postgresql test environment and run tests
    - name: Setup postgresql cli tool
      run: apt-get update && apt-get install --yes postgresql-client
    - run: psql -h postgres -U postgres -c 'create database testdb;'
    - run: psql -c 'create database prisma_shadow;' -U postgres
    - run: psql -c 'create database rays_shadow;' -U postgres
    - name: Testing against postgresql db
      run: npm test:ci:postgresql

#    - run: npm test:ci:sqlite
